### ISSUE TITLE
invlpg is available ?

### ISSUE THREAD

**Issue by starnakin** [BolvicBolvicovic/kfs#1]
Hello,

I'm currently working on the KFS-3 project and noticed that `invlpg` has only been available since the i486 (https://wiki.osdev.org/TLB). Am I missing something?

Thanks!

**Comment by BolvicBolvicovic** [comment]
Hello,

No, you are not missing anything! If you want to accomplish a similar task,
you just need to reload cr3 to make a tlb flush. I forgot to do it when I
switch table the second time but you can see the assembly as I do it when I
activate paging in my kernel/start.s file.


Good evening !
